version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda-dynamo-ts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vccewkk45rls"
s3_prefix = "sam-lambda-dynamo-ts"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
